### ISSUE TITLE
DocCreator segfaults

### ISSUE THREAD

**Issue by bertsky** [DocCreator/DocCreator#15]
After doing font extraction and layout extraction (filling with lorem ipsum), saving the XML and reopening, whenever I click on a region, I get the following segmentation violation crash:

<details> <summary>gdb stack frame</summary>

```
Thread 1 "DocCreator" received signal SIGSEGV, Segmentation fault.
Models::Font::getCharacter (this=this@entry=0x0, charValue=...)
    at DocCreator/framework/src/models/font.cpp:61
61	  auto it = _characterMap.find(charValue);
(gdb) bt full
#0  Models::Font::getCharacter(QString const&) const (this=this@entry=0x0, charValue=...)
    at DocCreator/framework/src/models/font.cpp:61
        it = <optimized out>
#1  0x000055555561cdbb in GraphicsTextBlockItem::drawCharacter(Doc::DocCharacter*, int, Doc::DocStyle*, Doc::DocParagraph*)
    (this=0x555557035600, c=0x5555574cb3c0, offset=0, style=0x555556d4e610, p=0x5555574cb270)
    at DocCreator/software/DocCreator/src/Document/GraphicsTextBlockItem.cpp:354
        docTextBlock = 0x5555574cb1e0
        cDisplay = {static null = {<No data fields>}, d = 0x5555574cb310}
        font = 0x0
        character = <optimized out>
        data = <optimized out>
        characterImage = <incomplete type>
        right = <optimized out>
        base = <optimized out>
        left = <optimized out>
        item = <optimized out>
#2  0x000055555561d23f in GraphicsTextBlockItem::drawString(Doc::DocString*, int, Doc::DocParagraph*)
    (this=this@entry=0x555557035600, s=s@entry=0x555556fc3620, offset=offset@entry=0, p=p@entry=0x5555574cb270) at DocCreator/software/DocCreator/src/Document/GraphicsTextBlockItem.cpp:291
        c = 0x5555574cb3c0
        __for_range = <optimized out>
#3  0x000055555561d31b in GraphicsTextBlockItem::drawParagraph(Doc::DocParagraph*, int)
    (this=0x555557035600, p=0x5555574cb270, offset=0)
    at DocCreator/software/DocCreator/src/Document/GraphicsTextBlockItem.cpp:275
        s = 0x555556fc3620
        __for_range = 
            @0x7fffffffc7b0: {<QListSpecialMethods<Doc::DocString*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x555556ea6e40}, d = 0x555--Type <RET> for more, q to quit, c to continue without paging--c
556ea6e40}}
#4  0x000055555561d4a1 in GraphicsTextBlockItem::draw(bool) (this=0x555557035600) at DocCreator/software/DocCreator/src/Document/GraphicsTextBlockItem.cpp:186
        p = 0x5555574cb270
        __for_range = @0x7fffffffc810: {<QListSpecialMethods<Doc::DocParagraph*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x555556981590}, d = 0x555556981590}}
        docTextBlock = 0x5555574cb1e0
        paragraphs = {<QListSpecialMethods<Doc::DocParagraph*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x555556981590}, d = 0x555556981590}}
        firstParagraph = <optimized out>
        offset = 0
#5  0x0000555555602456 in ADocumentView<Doc::DocTextBlock>::drawElement(Doc::DocTextBlock*, bool) (this=this@entry=0x555557035680, element=<optimized out>, complete=complete@entry=false) at DocCreator/software/DocCreator/src/Document/ADocumentView.hpp:40
#6  0x00005555556046d1 in ADocumentView<Doc::DocTextBlock>::drawElement(Doc::DocTextBlock*, bool) (complete=false, element=<optimized out>, this=0x555557035680) at DocCreator/software/DocCreator/src/Document/ADocumentView.hpp:40
        graphicTextBlock = 0x555557035600
        docTextBlock = <optimized out>
        currentBlock = 0x555557035600
        page = 0x555556fec6e0
        current = <optimized out>
        it1 = <optimized out>
        it1End = <optimized out>
#7  GraphicsPageItem::draw(bool) (this=0x555556a2a9d0, complete=<optimized out>) at DocCreator/software/DocCreator/src/Document/GraphicsPageItem.cpp:222
        graphicTextBlock = 0x555557035600
        docTextBlock = <optimized out>
        currentBlock = 0x555557035600
        page = 0x555556fec6e0
        current = <optimized out>
        it1 = <optimized out>
        it1End = <optimized out>
#8  0x0000555555618676 in ADocumentView<Doc::Page>::drawElement(Doc::Page*, bool) (this=0x555556a2a9e0, element=<optimized out>, complete=<optimized out>) at DocCreator/software/DocCreator/src/Document/ADocumentView.hpp:40
#9  0x000055555561b213 in ADocumentView<Doc::Document>::drawElement(Doc::Document*, bool) (complete=false, element=0x555556d785b0, this=0x555556977920) at DocCreator/software/DocCreator/src/Document/ADocumentView.hpp:40
        document = 0x555556d785b0
#10 ADocumentView<Doc::Document>::drawElement(Doc::Document*, bool) (complete=false, element=0x555556d785b0, this=0x555556977920) at DocCreator/software/DocCreator/src/Document/ADocumentView.hpp:40
        document = 0x555556d785b0
#11 DocumentView::draw(bool) (this=<optimized out>, complete=<optimized out>) at DocCreator/software/DocCreator/src/Document/DocumentView.cpp:148
        document = 0x555556d785b0
#12 0x0000555555605686 in ADocumentView<Doc::Document>::drawElement(Doc::Document*, bool) (this=0x5555563136e0, element=<optimized out>, complete=complete@entry=false) at DocCreator/software/DocCreator/src/Document/ADocumentView.hpp:40
#13 0x0000555555605bf5 in ADocumentView<Doc::Document>::drawElement(Doc::Document*, bool) (complete=false, element=<optimized out>, this=<optimized out>) at DocCreator/software/DocCreator/src/Document/ADocumentView.hpp:40
        currentTextBlock = <optimized out>
        currentStyle = 0x555556d4e610
#14 DocumentController::setOffset(int) (this=0x5555567e24a0, value=<optimized out>) at DocCreator/software/DocCreator/src/Document/DocumentController.cpp:366
        currentTextBlock = <optimized out>
        currentStyle = 0x555556d4e610
#15 0x000055555561c586 in GraphicsTextBlockItem::setCursorFromPosition(QPointF) (this=this@entry=0x555557035600, pos=...) at DocCreator/software/DocCreator/src/Document/GraphicsCharacterItem.hpp:29
        isReturn = <optimized out>
        cursorBefore = <optimized out>
        controller = <optimized out>
        charItem = 0x555556d6af40
        __for_range = @0x5555570356b0: {<QListSpecialMethods<GraphicsCharacterItem*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffff6738760 <QListData::shared_null>}, d = 0x7ffff6738760 <QListData::shared_null>}}
#16 0x000055555561c702 in GraphicsTextBlockItem::mousePressEvent(QGraphicsSceneMouseEvent*) (this=0x555557035600, event=<optimized out>) at DocCreator/software/DocCreator/src/Document/GraphicsTextBlockItem.cpp:441
        docController = <optimized out>
        docTextBlock = 0x5555574cb1e0
#17 0x00007ffff7537b4a in QGraphicsItem::sceneEvent(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff755b627 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff7563acb in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff7563cff in QGraphicsScene::mousePressEvent(QGraphicsSceneMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff756d27a in QGraphicsScene::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff7230a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff723a0f0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff665593a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff758a22b in QGraphicsView::mousePressEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff72732d1 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff7320d52 in QFrame::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff758b421 in QGraphicsView::viewportEvent(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff665564b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff7230a55 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007ffff723a343 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007ffff665593a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff7239457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007ffff728f35d in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff72921ec in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007ffff7230a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007ffff723a0f0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007ffff665593a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00007ffff6bff7d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#40 0x00007ffff6c0110b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#41 0x00007ffff6bdb35b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#42 0x00007fffeb49132e in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#43 0x00007ffff482a17d in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007ffff482a400 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#45 0x00007ffff482a4a3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007ffff66ad565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x00007ffff66544db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#48 0x00007ffff665c246 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#49 0x00005555555a5d49 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at DocCreator/software/DocCreator/src/main.cpp:47
        a = <incomplete type>
        w = 0x555555fee580
```

</details>

(I can also share the core dump upon request.)

Not sure what exactly you need to reproduce, so I have packaged all data files you might need:

[doccreator-crash.zip](https://github.com/DocCreator/DocCreator/files/7565315/doccreator-crash.zip)

My platform:
- Linux Mint 20 x86_64
- DocCreator aedf944f957a07bc8386a32a81e0015d122bdc4f (cmake build with GCC c++ 9.3.0)
- QT 5.12
- OpenCV 4.2.0
- cmake 3.16.3

**Comment by BorisMansencal** [comment]
Hi,

Thank you for your interest in DocCreator.

Could you try the development branch "pybind11" ? Do you have the same crash ? 
The version of DocCreator on this branch now uses binary files to store the fonts. You will need to convert your font file from an .of ascii file to a .bof binary file, with the tool tools/convertOF.  I have done it for your font file, the new file is here: https://dept-info.labri.fr/~mansenca/boersenblatt-fraktur.bof

**Comment by bertsky** [comment]
Hi,
thanks for your help (and sorry I couldn't get back to you sooner)!

I can confirm this prevents the crash. (I chose "Load font..." on the .bof, did not even remove the .of file from the font dir.)
